### ISSUE TITLE
Unable to decrypt Ghost of Tsushima PC files

### ISSUE THREAD

**Issue by Foul-Tarnished** [GaticusHax/libPSARC#3]
**Describe the bug**
Unable to decrypt psarc archives from **Ghost of Tsushima Director's Cut** (PC version)
I tried with https://github.com/MilchRatchet/PSArcInterface (use libPSARC) but it doesn't work

**Expected behavior**
Extract files contained in .psarc archives

**Steps To Reproduce**
- download PSArcInterface 
- ``.\psarc-cl.exe unpack .\gapack_misc_b.psarc output``

```
PSArc-cl - refs/tags/v1
Failed to synchronize with archive.
```

**File**
[gapack_misc_b.zip](https://github.com/GaticusHax/libPSARC/files/15359430/gapack_misc_b.zip)

**Comment by MilchRatchet** [comment]
Hi, I think there is some confusion here. You were using the commandline tool from https://github.com/MilchRatchet/PSArcInterface which uses a library that is called LibPSArc from that same repository. However, that LibPSArc is not the same as the libPSARC in this repository despite them having the same name.

Hence this issue is unrelated to this repository and should be closed.
